### PR TITLE
Some minor UI enhancements

### PR DESCRIPTION
**Pull request by mathieucarbou**
This is highly subjective, feel free to take, modify, delete ;-)

Main interesting thing is the widening of the console which is too short in width.

### CODE REVIEW

**Comment by asjdf** [comment]
Thank you for your PR.

It seems that you have made some optimizations for the experience of small-screen devices and optimized the prompt when the WebSocket is disconnected.  Can you provide a screenshot of the effect after the style change? Unfortunately I don't have a development environment on hand so it's not easy to review these changes.

By the way, would you mind to update the `WebSerialWebPage.h`? Because the web page will eventually be stored in the firmware. The specific update method is explained in [https://github.com/asjdf/WebSerialLite/blob/main/frontend/README.md](https://github.com/asjdf/WebSerialLite/blob/main/frontend/README.md)

**Comment by mathieucarbou** [comment]
Here is a screenshot ;-) the internal text area now resize with the browser.
image

**Comment by asjdf** [comment]
Oh, this style change is indeed quite big, I'm not sure if other users like this change. 

Regardless of style, I think there is indeed merit in handling some errors. In addition, I see that you also use some ANSI color definitions (I'm not sure what to call this thing). I think it would be very cool if the color display could be implemented with very low firmware space usage.

Thanks again for your PR. ❤️

**Comment by mathieucarbou** [comment]
No problem :-) Like I said this is a very subjective PR, it does not bring any feature or fix ;-)

I am using colors for the logs only in debug mode with the platformio serial console. That's why the code is leaking here. I agree that supporting that would be nice! But this is not possible in a textarea and I am not fluent in html and css enough to do that.

**Pull request closed without merging**
